# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20180301_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='adders',
        ),
        migrations.AlterField(
            model_name='product',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adding', to='registration.User'),
        ),
    ]
