# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20180301_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='joiners',
            field=models.ManyToManyField(related_name='joiner', to='registration.User'),
        ),
    ]
